import type { Metadata } from "next";
import Menu from "@/components/menu";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThirdwebProvider } from "@/lib/thirdwebprovider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThirdwebProvider
      
      authConfig={{
        domain: process.env.NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN as string,
        authUrl: "/api/auth/",
      }}
      
    >
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased bg-[#000000]"
          )}
        >
          <Menu />
          {children}
        </body>
      </html>
    </ThirdwebProvider>
  );
}
